FROM ubuntu:18.04

ARG DOCKER_ENGINE_VERSION
ARG DOCKER_COMPOSE_VERSION

ENV DOCKER_ENGINE_VERSION=${DOCKER_ENGINE_VERSION} \
    DOCKER_COMPOSE_VERSION=${DOCKER_COMPOSE_VERSION}

# Install Java Development Kit, Git, and cURL
RUN apt-get update && apt-get install -y \
      git \
      curl \
      default-jdk \
      make python python-requests python-yaml \
      && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/run/sshd

# Get Docker Engine binaries
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_ENGINE_VERSION}.tgz && \
    tar --strip-components=1 -xvzf docker-${DOCKER_ENGINE_VERSION}.tgz -C /usr/local/bin && \
    rm docker-${DOCKER_ENGINE_VERSION}.tgz && \
    docker --version

# Install Docker Compose
RUN curl -fsSL https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    docker-compose --version

VOLUME /var/run/docker.sock
